# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddeff8ed89d32c98a7275edf24037882bc1f6ff84352079acdab34a9a4e87437c49fecd71999f7f4926199c9c8481a40e4ce2fd4cf90487504b5e9c563b9c796

test:
  secret_key_base: 90a481f83f1e8d541f06ae6a5639abe6716725e9103fd0a543d611c127686a8ad1a34b8449fd97e3a52f74a15962c7ff58a4a9d53186a18c56ac22ddffebc3e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
